# Generated by Django 2.2 on 2024-06-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='note',
            new_name='list',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='deadLine',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='subTitle',
        ),
    ]
