# Generated by Django 2.2 on 2024-06-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20240607_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='list',
        ),
    ]
